apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: weatherhub
type: Opaque
data:
  POSTGRES_USER: YzY0MjZmYjY3NDEyZTlkMWQwYjlkZGQ0OWRiNDM0MWI=
  POSTGRES_PASSWORD: d2VhdGhlcnBhc3N3b3Jk
  POSTGRES_DB: d2VhdGhlcmh1Yg==
  OPENWEATHER_API_KEY: eW91ci1hcGkta2V5
  DATABASE_URL: eW91ci1kYXRhYmFzZS11cmw=
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0
  TWILIO_ACCOUNT_SID: eW91ci10d2lsaW8tc2lk
  TWILIO_AUTH_TOKEN: eW91ci10d2lsaW8tYXV0aC10b2tlbg==
  SENDGRID_API_KEY: U0s4MDVhMjNkNDMwOTczMTJlMGFhNWYwNjZiNjBlNjc5Ng==  ""
